# Generated by Django 4.2.2 on 2023-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cate',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
