# Generated by Django 4.2.2 on 2023-06-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_review_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='dinereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField()),
                ('seat', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
