# Generated by Django 4.2.2 on 2023-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_dinereq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinereq',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
    ]
