# Generated by Django 4.2.2 on 2023-06-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_finalord_paymentid_alter_finalord_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalord',
            name='payorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOME.order'),
        ),
    ]
